### ISSUE TITLE
Issue with connectivity check: DeepL blocking connection when UA isn't specified

### ISSUE THREAD

**Issue by mlazzarotto** [DavidG33k/Flow.Launcher.Plugin.DeepFlow#2]
Hi Davide, first and foremost, thank you for this beautiful plugin, it's very useful to me.
I've been using this for a while now, and for the past several months I've found that whatever query I was writing, I always had "Invalid Notation or No Internet Connection!" message.

I've troubleshooted the problem and turns out that the call you make [here](https://github.com/DavidG33k/Flow.Launcher.Plugin.DeepFlow/blob/277a502b166c47386de4042f1ca9c0877f0b8136/plugin/Engine.py#L76C1-L76C1) returns "HTTP Error 403: Forbidden".
To temporarely solve this, I've added the same user agent you are using for the translation, by replacing this
``` python
urllib.request.urlopen("https://www.deepl.com/translator")
```
with this
``` python
headers = {'User-Agent': "Edge, Brave, Firefox, Chrome, Opera"}
url = "https://www.deepl.com/translator"
req = urllib.request.Request(url, headers=headers)
urllib.request.urlopen(req)
```

**Comment by DangerousComrade** [comment]
> Hi Davide, first and foremost, thank you for this beautiful plugin, it's very useful to me. I've been using this for a while now, and for the past several months I've found that whatever query I was writing, I always had "Invalid Notation or No Internet Connection!" message.
> 
> I've troubleshooted the problem and turns out that the call you make [here](https://github.com/DavidG33k/Flow.Launcher.Plugin.DeepFlow/blob/277a502b166c47386de4042f1ca9c0877f0b8136/plugin/Engine.py#L76C1-L76C1) returns "HTTP Error 403: Forbidden". To temporarely solve this, I've added the same user agent you are using for the translation, by replacing this
> 
> ```python
> urllib.request.urlopen("https://www.deepl.com/translator")
> ```
> 
> with this
> 
> ```python
> headers = {'User-Agent': "Edge, Brave, Firefox, Chrome, Opera"}
> url = "https://www.deepl.com/translator"
> req = urllib.request.Request(url, headers=headers)
> urllib.request.urlopen(req)
> ```

Hey bro! thank you so much for this code. I've been looking for this.

**Comment by DavidG33k** [comment]
Hi Marco, thank you so much for your support :)
It’s important to always specify a User Agent when a request is made, it was my oversight. As soon as I have time, I will apply the fix and update the release.
Leave the issuee open, I will close it once resolved.

**Comment by DavidG33k** [comment]
Hi, sorry again for the delay. I updated the plugin, it seems to work now, could you try it?

**Comment by mlazzarotto** [comment]
> Hi, sorry again for the delay. I updated the plugin, it seems to work now, could you try it?

Hi Davide, I've just tried the new version, and it worked fine. Thank you for the support and the effort. 👏
